Update README.md
kodi-pvr/pvr.vuplus pull request #223
Opened 2019-05-08 09:55 UTC by bservet

Here's the update again....

2019-05-08 11:36 UTC, phunkyfish requested changes

2019-05-08 11:36 UTC, phunkyfish commented on README.md
> +* **Update interval**: As the set-top box can also be used to modify timers, delete recordings etc. and the set-top box does not notify the Kodi installation, the addon needs to regularly check for u
Extra spaces at the end of the line.

2019-05-08 11:37 UTC, phunkyfish commented
Once this is cleaned up and approved you will also want to have a similar PR for the Leia branch.

2019-05-08 18:54 UTC, phunkyfish commented
Can you squash this into the single commit?

2019-05-09 12:24 UTC, bservet commented
Ok, this commit has the spaces so'll close it as I still haven't found the squash option.

2019-05-09 12:24 UTC, closed without merging

2019-05-09 12:49 UTC, phunkyfish commented
Ok, so just create a new one for matrix with a single commit. The Leia one is OK.